openapi: 3.1.0
info:
  title: BRP API Gebeurtenissen
  version: 1.0.0
  description: OAS specificatie geclassificeerde events
paths:
  /event:
    post:
      operationId: publishEvent
      summary: Publiceer events
      requestBody:
          content:
            application/json:
              schema:
                $ref: "classificatie-service-events/classificatie-event.yaml#/components/schemas/Event"
      responses: 
        201:
          description: Event succesvol gepubliceerd
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unieke identificatie van het gepubliceerde event
          