openapi: 3.1.0
info:
  title: BRP API Gebeurtenissen
  version: 1.0.0
  description: Voorbeeld OAS specificatie IngeschrevenEvent
paths:
  /event/ingeschreven:
    get:
      summary: Haal events op
      responses:
        "200":
          description: Een ingeschreven event
          content:
            application/json:
              schema:
                $ref: "classificatie-service-events/ingeschreven-event.yaml#/components/schemas/IngeschrevenEvent"
  /event/verhuisd:
    get:
      summary: Haal events op
      responses:
        "200":
          description: Een verhuisd event
          content:
            application/json:
              schema:
                $ref: "classificatie-service-events/verhuisd-event.yaml#/components/schemas/VerhuisdEvent"
